# Site settings
title: TNT Transportation
email: tnttransportationxl@gmail.com
description: Todd's Taxi Service.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "tnttransportationxl.com" # the base hostname & protocol for your site e.g. http://yvesespinosa.com
#download_button_url: ""

# Social settings
#500px_url:
#facebook_url:
#github_url:
#gitlab_url: 
#googleplus_url: 
#instagram_url:
#linkedin_url: 
#pinterest_url:
#twitter_url:  

# Build settings
markdown: kramdown

collections:
  parts:
    output: false
