# config.yml
backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: toddcheever/toddcheever
media_folder: 'assets'

collections:
  - name: 'sections'
    label: 'Sections'
    folder: '_parts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
