# config.yml
backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: toddcheever/toddcheever
media_folder: 'assets'

collections:
  - name: 'parts'
    label: 'sections'
    folder: '_parts/'
    create: true
    editor:
      preview: false
    fields:
      name: "items"
      widget: "list"
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
